import React,{useState} from 'react';
import {View,Text,TouchableOpacity,ScrollView,StyleSheet} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import {useTranslation} from 'react-i18next';
import {Ionicons} from '@expo/vector-icons';
import {COLORS} from '../../config';
const PLANS=[{id:1,name:'Weekly',price:'$2.69',badge:null,popular:false},{id:2,name:'Yearly',price:'$41.99',badge:'Save 70%',popular:true},{id:3,name:'Lifetime',price:'$68.99',badge:'Pay once',popular:false}];
export default function SubscriptionScreen({navigation}:any){const{t}=useTranslation();const[sel,setSel]=useState(2);
const features=['Ad-Free Experience','Full Audio Library','AI Assistant Access','Offline Downloads','Advanced Tajweed','Premium Quran Search'];
return(<SafeAreaView style={s.c}><TouchableOpacity style={{padding:16}} onPress={()=>navigation.goBack()}><Ionicons name="close" size={24} color={COLORS.text}/></TouchableOpacity>
<ScrollView contentContainerStyle={s.scroll}><View style={s.hero}><View style={s.ic}><Text style={{fontSize:34,color:'#fff'}}>☪</Text></View><Text style={s.ht}>Focus on your Deen</Text><Text style={s.hs}>Unlock all premium features</Text></View>
<View style={s.fl}>{features.map((f,i)=>(<View key={i} style={s.fr}><Ionicons name="checkmark-circle" size={20} color={COLORS.success}/><Text style={s.ft}>{f}</Text></View>))}</View>
<View style={s.pl}>{PLANS.map(p=>(<TouchableOpacity key={p.id} style={[s.pc,sel===p.id&&s.pca]} onPress={()=>setSel(p.id)}><View style={s.radio}><View style={[s.ri,sel===p.id&&s.ria]}/></View><View style={{flex:1}}><Text style={s.pn}>{p.name}</Text>{p.popular&&<Text style={s.pop}>{t('subscription.most_popular')}</Text>}</View><View style={{alignItems:'flex-end'}}>{p.badge&&<View style={s.sb}><Text style={s.sbt}>{p.badge}</Text></View>}<Text style={s.pp}>{p.price}</Text></View></TouchableOpacity>))}</View>
<Text style={s.trial}>{t('subscription.free_trial')}</Text><Text style={s.cancel}>{t('subscription.cancel_anytime')}</Text>
<TouchableOpacity style={s.btn}><Text style={s.btnTxt}>{t('subscription.subscribe')}</Text></TouchableOpacity></ScrollView></SafeAreaView>);}
const s=StyleSheet.create({c:{flex:1,backgroundColor:'#fff'},scroll:{paddingHorizontal:24,paddingBottom:40},hero:{alignItems:'center',marginBottom:24},ic:{width:70,height:70,borderRadius:35,backgroundColor:COLORS.primary,justifyContent:'center',alignItems:'center',marginBottom:14},ht:{fontSize:24,fontWeight:'700',color:COLORS.text},hs:{fontSize:15,color:COLORS.textSecondary,marginTop:4},fl:{marginBottom:24,gap:12},fr:{flexDirection:'row',alignItems:'center',gap:10},ft:{fontSize:15,color:COLORS.text},pl:{gap:12,marginBottom:16},pc:{flexDirection:'row',alignItems:'center',padding:16,borderWidth:1.5,borderColor:COLORS.border,borderRadius:14},pca:{borderColor:COLORS.primary,backgroundColor:COLORS.primaryLight+'30'},radio:{width:22,height:22,borderRadius:11,borderWidth:2,borderColor:COLORS.border,justifyContent:'center',alignItems:'center',marginRight:14},ri:{width:12,height:12,borderRadius:6},ria:{backgroundColor:COLORS.primary},pn:{fontSize:15,fontWeight:'600',color:COLORS.text},pop:{fontSize:11,color:COLORS.primary,fontWeight:'500',marginTop:2},sb:{backgroundColor:COLORS.error,paddingHorizontal:8,paddingVertical:2,borderRadius:4,marginBottom:4},sbt:{fontSize:10,fontWeight:'700',color:'#fff'},pp:{fontSize:17,fontWeight:'700',color:COLORS.text},trial:{textAlign:'center',fontSize:15,fontWeight:'500',color:COLORS.primary,marginBottom:4},cancel:{textAlign:'center',fontSize:13,color:COLORS.textTertiary,marginBottom:20},btn:{backgroundColor:COLORS.primary,borderRadius:10,paddingVertical:16,alignItems:'center'},btnTxt:{fontSize:17,fontWeight:'600',color:'#fff'}});
