import React,{useState,useRef} from 'react';
import {View,Text,TextInput,TouchableOpacity,FlatList,StyleSheet,KeyboardAvoidingView,Platform,ActivityIndicator} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import {useTranslation} from 'react-i18next';
import {Ionicons} from '@expo/vector-icons';
import {COLORS} from '../../config';
import {aiAPI} from '../../api/client';
interface Msg{id:string;role:'user'|'assistant';content:string}
export default function AIAssistantScreen({navigation}:any){const{t}=useTranslation();const[msgs,setMsgs]=useState<Msg[]>([]);const[input,setInput]=useState('');const[loading,setLoading]=useState(false);const[convId,setConvId]=useState<number|undefined>();const ref=useRef<FlatList>(null);
const send=async()=>{const q=input.trim();if(!q||loading)return;const um:Msg={id:Date.now().toString(),role:'user',content:q};setMsgs(p=>[...p,um]);setInput('');setLoading(true);
try{const r=await aiAPI.ask(q,convId);const d=r.data?.data;if(d?.conversation_id)setConvId(d.conversation_id);setMsgs(p=>[...p,{id:(Date.now()+1).toString(),role:'assistant',content:d?.message?.content||'No response'}]);}catch(e:any){setMsgs(p=>[...p,{id:(Date.now()+1).toString(),role:'assistant',content:e.response?.data?.message||'Failed to get response. Connect the Odoo backend with AI configured.'}]);}finally{setLoading(false);}};
return(<SafeAreaView style={s.c}><View style={s.h}><TouchableOpacity onPress={()=>navigation.goBack()}><Ionicons name="arrow-back" size={24} color={COLORS.text}/></TouchableOpacity><View style={{flex:1,alignItems:'center'}}><Text style={s.ht}>{t('ai.assistant')}</Text></View><View style={{width:24}}/></View>
<FlatList ref={ref} data={msgs} keyExtractor={i=>i.id} contentContainerStyle={s.list} onContentSizeChange={()=>ref.current?.scrollToEnd()} ListEmptyComponent={<View style={s.empty}><Ionicons name="sparkles" size={48} color={COLORS.primaryLight}/><Text style={s.et}>{t('ai.assistant')}</Text><Text style={s.es}>Ask any question about Islam, Quran, Hadith, or daily worship</Text></View>}
renderItem={({item})=>(<View style={[s.mr,item.role==='user'&&{alignItems:'flex-end'}]}><View style={[s.mb,item.role==='user'?s.ub:s.ab]}><Text style={[s.mt,item.role==='user'&&{color:'#fff'}]}>{item.content}</Text></View></View>)}/>
{loading&&<View style={s.typing}><ActivityIndicator size="small" color={COLORS.primary}/><Text style={s.tt}>{t('ai.thinking')}</Text></View>}
<KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} keyboardVerticalOffset={90}><View style={s.ib}><TextInput style={s.inp} value={input} onChangeText={setInput} placeholder={t('ai.ask_question')} placeholderTextColor={COLORS.textTertiary} multiline maxLength={500}/><TouchableOpacity style={[s.send,(!input.trim()||loading)&&{opacity:0.5}]} onPress={send} disabled={!input.trim()||loading}><Ionicons name="send" size={20} color="#fff"/></TouchableOpacity></View></KeyboardAvoidingView></SafeAreaView>);}
const s=StyleSheet.create({c:{flex:1,backgroundColor:'#fff'},h:{flexDirection:'row',alignItems:'center',padding:16,borderBottomWidth:0.5,borderBottomColor:COLORS.border},ht:{fontSize:17,fontWeight:'600',color:COLORS.text},list:{paddingHorizontal:16,paddingVertical:16,flexGrow:1},mr:{marginBottom:12},mb:{maxWidth:'85%',borderRadius:14,padding:14},ub:{backgroundColor:COLORS.primary,borderBottomRightRadius:4},ab:{backgroundColor:COLORS.backgroundSecondary,borderBottomLeftRadius:4},mt:{fontSize:15,lineHeight:22,color:COLORS.text},typing:{flexDirection:'row',alignItems:'center',paddingHorizontal:24,paddingBottom:8,gap:8},tt:{fontSize:13,color:COLORS.textTertiary},ib:{flexDirection:'row',alignItems:'flex-end',paddingHorizontal:16,paddingVertical:10,borderTopWidth:0.5,borderTopColor:COLORS.border,gap:10},inp:{flex:1,minHeight:42,maxHeight:120,backgroundColor:COLORS.backgroundSecondary,borderRadius:14,paddingHorizontal:16,paddingVertical:10,fontSize:15,color:COLORS.text},send:{width:42,height:42,borderRadius:21,backgroundColor:COLORS.primary,justifyContent:'center',alignItems:'center'},empty:{flex:1,justifyContent:'center',alignItems:'center',paddingTop:100},et:{fontSize:20,fontWeight:'600',color:COLORS.text,marginTop:16},es:{fontSize:15,color:COLORS.textSecondary,textAlign:'center',marginTop:8,paddingHorizontal:40}});
